services:
  mysql-db:
    image: docker.io/bitnami/mysql:8.4
    container_name: mysql-db
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - spring-net
    volumes:
      - mysql-data:/bitnami/mysql/data
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6

  order-service:
    image: ghcr.io/gustavhaavik/commercify_orders:latest
    container_name: commercify_orders
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/orderdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - spring-net

  payment-service:
    image: ghcr.io/gustavhaavik/commercify_payments:latest
    container_name: commercify_payments
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/paymentdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - spring-net

  product-service:
    image: ghcr.io/gustavhaavik/commercify_products:latest
    container_name: commercify_products
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/productdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - spring-net

  user-service:
    image: ghcr.io/gustavhaavik/commercify_users:latest
    container_name: commercify_users
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/userdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
