name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      # Set up Java for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Spring Boot applications using Maven
      - name: Build payment-service JAR
        run: mvn clean package -DskipTests
        working-directory: PaymentService

      - name: Build product-service JAR
        run: mvn clean package -DskipTests
        working-directory: ProductsService

      - name: Build order-service JAR
        run: mvn clean package -DskipTests
        working-directory: OrderService

      - name: Build user-service JAR
        run: mvn clean package -DskipTests
        working-directory: UserService

      - name: Build discovery-server JAR
        run: mvn clean package -DskipTests
        working-directory: DiscoveryServer

      - name: Build api-gateway JAR
        run: mvn clean package -DskipTests
        working-directory: ApiGateway

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push discovery-server image
        run: |
          docker build -t ghcr.io/gustavhaavik/commercify_discoveryserver:latest ./DiscoveryServer
          docker push ghcr.io/gustavhaavik/commercify_discoveryserver:latest

      - name: Build and push api-gateway image
        run: |
          docker build -t ghcr.io/gustavhaavik/commercify_apigateway:latest ./ApiGateway
          docker push ghcr.io/gustavhaavik/commercify_apigateway:latest

      - name: Build and push payment-service image
        run: |
          docker build -t ghcr.io/gustavhaavik/commercify_payments:latest ./PaymentsService
          docker push ghcr.io/gustavhaavik/commercify_payments:latest

      - name: Build and push product-service image
        run: |
          docker build -t ghcr.io/gustavhaavik/commercify_products:latest ./ProductsService
          docker push ghcr.io/gustavhaavik/commercify_products:latest

      - name: Build and push order-service image
        run: |
          docker build -t ghcr.io/gustavhaavik/commercify_orders:latest ./OrderService
          docker push ghcr.io/gustavhaavik/commercify_orders:latest

      - name: Build and push user-service image
        run: |
          docker build -t ghcr.io/gustavhaavik/commercify_users:latest ./UserService
          docker push ghcr.io/gustavhaavik/commercify_users:latest
