name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      # Set up Java for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Build the Spring Boot applications using Maven
      - name: Build payment-service JAR
        run: |
          cd PaymentsService
          mvn clean package -DskipTests
        working-directory: ./PaymentsService

      - name: Build product-service JAR
        run: |
          cd ProductsService
          mvn clean package -DskipTests
        working-directory: ./ProductsService

      - name: Build order-service JAR
        run: |
          cd OrderSerivce
          mvn clean package -DskipTests
        working-directory: ./OrderSerivce

      - name: Build user-service JAR
        run: |
          cd UserService
          mvn clean package -DskipTests
        working-directory: ./UserService

      - name: Build discovery-server JAR
        run: |
          cd DiscoveryServer
          mvn clean package -DskipTests
        working-directory: ./DiscoveryServer

      - name: Build api-gateway JAR
        run: |
          cd ApiGateway
          mvn clean package -DskipTests
        working-directory: ./ApiGateway

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:latest ./microservices-frontend
          docker push ghcr.io/${{ github.repository }}/frontend:latest

      - name: Build and push discovery-server image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/discovery-server:latest ./discovery-server
          docker push ghcr.io/${{ github.repository }}/discovery-server:latest

      - name: Build and push api-gateway image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/api-gateway:latest ./api-gateway
          docker push ghcr.io/${{ github.repository }}/api-gateway:latest

      - name: Build and push payment-service image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/payment-service:latest ./payment-service
          docker push ghcr.io/${{ github.repository }}/payment-service:latest

      - name: Build and push product-service image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/product-service:latest ./product-service
          docker push ghcr.io/${{ github.repository }}/product-service:latest

      - name: Build and push order-service image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/order-service:latest ./order-service
          docker push ghcr.io/${{ github.repository }}/order-service:latest

      - name: Build and push user-service image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/user-service:latest ./user-service
          docker push ghcr.io/${{ github.repository }}/user-service:latest
